# Site settings
author: Matt W Pitner
title: Matt's Blog
header-img: img/home-bg.png
email: mattpitner09@gmail.com
copyright_name: Matt W Pitner
description: > # this means to ignore newlines until "baseurl:"
  A collection of my experiences in the world of programming. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mattpitner

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
